version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        env_file:
            - env
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A core worker -l INFO --uid=nobody
        volumes:
            - .:/usr/src/app
        env_file:
            - env
        depends_on:
            - django
            - redis
    pgdb:
        image: "postgres:12.7"
        container_name: pgdb
        environment:
            - POSTGRES_DB=db
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        volumes:
            - pgdata:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
    redis:
        image: "redis:6.2.4"
        volumes:
          - ./redis.conf:/usr/local/etc/redis/redis.com
        command: "redis-server /usr/local/etc/redis/redis.com"
        ports:
          - "6379:6379"
volumes:
  pgdata:
